# Generated by Django 4.2.1 on 2023-05-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_item_delete_motorcycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',), 'verbose_name_plural': 'Items'},
        ),
    ]
